//------------------------------------------------------------------------
// Copyright(c) 2023 Baron von Wenzelheimer.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Morsalyzer.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Morsalyzer VST3 (64Bit)"
#else
#define stringFileDescription	"Morsalyzer VST3"
#endif
#define stringCompanyName		"Baron von Wenzelheimer\0"
#define stringLegalCopyright	"Copyright(c) 2023 Baron von Wenzelheimer."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
